// constexpr-perf.cpp                                                 -*-C++-*-
// ----------------------------------------------------------------------------
//  Copyright (C) 2016 Dietmar Kuehl http://www.dietmar-kuehl.de         
//                                                                       
//  Permission is hereby granted, free of charge, to any person          
//  obtaining a copy of this software and associated documentation       
//  files (the "Software"), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify,        
//  merge, publish, distribute, sublicense, and/or sell copies of        
//  the Software, and to permit persons to whom the Software is          
//  furnished to do so, subject to the following conditions:             
//                                                                       
//  The above copyright notice and this permission notice shall be       
//  included in all copies or substantial portions of the Software.      
//                                                                       
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES      
//  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND             
//  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT          
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,         
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING         
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR        
//  OTHER DEALINGS IN THE SOFTWARE. 
// ----------------------------------------------------------------------------

#include "cf/map0.h"
#include "cf/map1.h"
#include "cf/map2.h"
#include "cf/map3.h"
#include "cf/string_view.h"
#include <iostream>

#ifndef SIZE
#    define SIZE 10
#endif
#ifndef MAP
#    define MAP make_map1
#endif

// ----------------------------------------------------------------------------

template <typename... P>
auto constexpr make_map(P... p) 
{
    return cf::MAP(p...);
}

// ----------------------------------------------------------------------------

using namespace cf::udl;
constexpr auto map = make_map(
#if 0 == SIZE
                              mp(5, 5)
                              , mp(1, 1)
                              , mp(4, 4)
                              , mp(3, 3)
                              , mp(2, 2)
#endif
#if 0 < SIZE
                              mp("one"_sv, 1)
                              , mp("two"_sv, 2)
                              , mp("three"_sv, 3)
                              , mp("four"_sv, 4)
                              , mp("five"_sv, 5)
                              , mp("six"_sv, 6)
                              , mp("seven"_sv, 7)
                              , mp("eight"_sv, 8)
                              , mp("nine"_sv, 9)
                              , mp("ten"_sv, 10)
#endif
#if 10 < SIZE
                              , mp("eleven"_sv, 11)
                              , mp("twelve"_sv, 12)
                              , mp("thirteen"_sv, 13)
                              , mp("fourteen"_sv, 14)
                              , mp("fifteen"_sv, 15)
                              , mp("sixteen"_sv, 16)
                              , mp("seventeen"_sv, 17)
                              , mp("eighteen"_sv, 18)
                              , mp("nineteen"_sv, 19)
                              , mp("twenty"_sv, 20)
#endif
#if 20 < SIZE
                              , mp("Acroba."_sv, 21)
                              , mp("Adobe"_sv, 22)
                              , mp("Akku"_sv, 23)
                              , mp("Akivierung"_sv, 24)
                              , mp("Akivierungen"_sv, 25)
                              , mp("Anbindung."_sv, 26)
                              , mp("Anforderungen"_sv, 27)
                              , mp("Anleiung,"_sv, 28)
                              , mp("Anschlieend"_sv, 29)
                              , mp("Anspruch,"_sv, 30)
#endif
#if 30 < SIZE
                              , mp("Anzeige"_sv, 31)
                              , mp("Auch"_sv, 32)
                              , mp("Auf"_sv, 33)
                              , mp("Bcher"_sv, 34)
                              , mp("Bcher."_sv, 35)
                              , mp("Bchern"_sv, 36)
                              , mp("Befehl-Shif-D"_sv, 37)
                              , mp("Befllen"_sv, 38)
                              , mp("Beim"_sv, 39)
                              , mp("Bildschirm"_sv, 40)
#endif
#if 40 < SIZE
                              , mp("BooCamp"_sv, 41)
                              , mp("Da"_sv, 42)
                              , mp("Dami"_sv, 43)
                              , mp("Danach"_sv, 44)
                              , mp("Das"_sv, 45)
                              , mp("Dazu"_sv, 46)
                              , mp("Den"_sv, 47)
                              , mp("Der"_sv, 48)
                              , mp("Deswegen"_sv, 49)
                              , mp("Deuschland"_sv, 50)
#endif
#if 50 < SIZE
                              , mp("Die"_sv, 51)
                              , mp("Digial"_sv, 52)
                              , mp("Digiale"_sv, 53)
                              , mp("Dokumenen"_sv, 54)
                              , mp("Durchbruch"_sv, 55)
                              , mp("EWAS"_sv, 56)
                              , mp("Ediionen"_sv, 57)
                              , mp("Ediions"_sv, 58)
                              , mp("Ediions."_sv, 59)
                              , mp("Ein"_sv, 60)
                              , mp("Einen"_sv, 61)
                              , mp("Einkaufen"_sv, 62)
                              , mp("Einkufe"_sv, 63)
                              , mp("Einkufe,"_sv, 64)
                              , mp("Elekroschro"_sv, 65)
                              , mp("Energie."_sv, 66)
                              , mp("Erfahrung"_sv, 67)
                              , mp("Ersens"_sv, 68)
                              , mp("Forma"_sv, 69)
                              , mp("Funkionali"_sv, 70)
                              , mp("Gadges,"_sv, 71)
                              , mp("Ganze"_sv, 72)
                              , mp("Geduld."_sv, 73)
                              , mp("Genuss"_sv, 74)
                              , mp("Ger"_sv, 75)
                              , mp("Ger,"_sv, 76)
                              , mp("Gere"_sv, 77)
                              , mp("Geren"_sv, 78)
                              , mp("Geres"_sv, 79)
                              , mp("Hilfe"_sv, 80)
                              , mp("Holz."_sv, 81)
                              , mp("ID"_sv, 82)
                              , mp("ID,"_sv, 83)
                              , mp("Ich"_sv, 84)
                              , mp("Idee"_sv, 85)
                              , mp("Ihnen"_sv, 86)
                              , mp("Ihren"_sv, 87)
                              , mp("Im"_sv, 88)
                              , mp("In"_sv, 89)
                              , mp("Insallaion"_sv, 90)
                              , mp("Kaufvorgang"_sv, 91)
                              , mp("Kilo"_sv, 92)
                              , mp("Krisenmeldungen"_sv, 93)
                              , mp("Lesefuer."_sv, 94)
                              , mp("Lesen"_sv, 95)
                              , mp("Los"_sv, 96)
                              , mp("Mac"_sv, 97)
                              , mp("Man"_sv, 98)
                              , mp("Mangel"_sv, 99)
                              , mp("Men"_sv, 100)
#endif
#if 100 < SIZE
                              , mp("Menge"_sv, 101)
                              , mp("Mo,"_sv, 102)
                              , mp("Momen"_sv, 103)
                              , mp("NACHRAG"_sv, 104)
                              , mp("NACHRAG:"_sv, 105)
                              , mp("Naja."_sv, 106)
                              , mp("Neubesizer"_sv, 107)
                              , mp("Normalerweise"_sv, 108)
                              , mp("Nur"_sv, 109)
                              , mp("OK"_sv, 110)
                              , mp("Oberflche"_sv, 111)
                              , mp("Odysee"_sv, 112)
                              , mp("Ordner"_sv, 113)
                              , mp("PC"_sv, 114)
                              , mp("PDFs"_sv, 115)
                              , mp("PRS-505"_sv, 116)
                              , mp("PRS-505."_sv, 117)
                              , mp("Papier"_sv, 118)
                              , mp("Parallels"_sv, 119)
                              , mp("Parallels),"_sv, 120)
                              , mp("Programm"_sv, 121)
                              , mp("Programmes"_sv, 122)
                              , mp("Punk"_sv, 123)
                              , mp("Reader"_sv, 124)
                              , mp("Rechner"_sv, 125)
                              , mp("Rechemanagemen"_sv, 126)
                              , mp("RockeBook"_sv, 127)
                              , mp("Schreibisch"_sv, 128)
                              , mp("Schrifdarsellung"_sv, 129)
                              , mp("Sofware"_sv, 130)
                              , mp("Sony"_sv, 131)
                              , mp("Spare"_sv, 132)
                              , mp("Saren"_sv, 133)
                              , mp("Srom"_sv, 134)
                              , mp("Sysem"_sv, 135)
                              , mp("age"_sv, 136)
                              , mp("asen"_sv, 137)
                              , mp("USB"_sv, 138)
                              , mp("Umblern"_sv, 139)
                              , mp("Und"_sv, 140)
                              , mp("Urlaubsgepck"_sv, 141)
                              , mp("User."_sv, 142)
                              , mp("Verfahren,"_sv, 143)
                              , mp("Vergleich"_sv, 144)
                              , mp("Version"_sv, 145)
                              , mp("Verwalen"_sv, 146)
                              , mp("Verwalung"_sv, 147)
                              , mp("Vielleich"_sv, 148)
                              , mp("Von"_sv, 149)
                              , mp("Weg"_sv, 150)
#endif
#if 150 < SIZE
                              , mp("Wel"_sv, 151)
                              , mp("Wenn"_sv, 152)
                              , mp("Wer"_sv, 153)
                              , mp("Windows"_sv, 154)
                              , mp("Windows."_sv, 155)
                              , mp("Wochen"_sv, 156)
                              , mp("Wre,"_sv, 157)
                              , mp("ZWEI:"_sv, 158)
                              , mp("Zugriff"_sv, 159)
                              , mp("Zweiens"_sv, 160)
                              , mp("abmelden,"_sv, 161)
                              , mp("abziehen,"_sv, 162)
                              , mp("allein"_sv, 163)
                              , mp("allein:"_sv, 164)
                              , mp("alles"_sv, 165)
                              , mp("alles,"_sv, 166)
                              , mp("als"_sv, 167)
                              , mp("am"_sv, 168)
                              , mp("an"_sv, 169)
                              , mp("angeboenen"_sv, 170)
                              , mp("angeh"_sv, 171)
                              , mp("angelege"_sv, 172)
                              , mp("angereen"_sv, 173)
                              , mp("anmelden."_sv, 174)
                              , mp("anschlieen."_sv, 175)
                              , mp("ansecken."_sv, 176)
                              , mp("auch"_sv, 177)
                              , mp("auf"_sv, 178)
                              , mp("auf."_sv, 179)
                              , mp("aufgeforder,"_sv, 180)
                              , mp("aufauchen,"_sv, 181)
                              , mp("aus"_sv, 182)
                              , mp("ausgesaeen"_sv, 183)
                              , mp("auswhlen."_sv, 184)
                              , mp("auorisier."_sv, 185)
                              , mp("auoisieren"_sv, 186)
                              , mp("basier"_sv, 187)
                              , mp("bauen"_sv, 188)
                              , mp("beenden,"_sv, 189)
                              , mp("beenden."_sv, 190)
                              , mp("bei"_sv, 191)
                              , mp("bekomm."_sv, 192)
                              , mp("benuzen"_sv, 193)
                              , mp("ber"_sv, 194)
                              , mp("besechend:"_sv, 195)
                              , mp("bis"_sv, 196)
                              , mp("bierer"_sv, 197)
                              , mp("brauch"_sv, 198)
                              , mp("brauch."_sv, 199)
                              , mp("bringen"_sv, 200)
#endif
#if 200 < SIZE
                              , mp("bzw."_sv, 201)
                              , mp("calibre"_sv, 202)
                              , mp("da"_sv, 203)
                              , mp("dann"_sv, 204)
                              , mp("darbende"_sv, 205)
                              , mp("darf"_sv, 206)
                              , mp("darin"_sv, 207)
                              , mp("das"_sv, 208)
                              , mp("dass"_sv, 209)
                              , mp("davon"_sv, 210)
                              , mp("dem"_sv, 211)
                              , mp("den"_sv, 212)
                              , mp("denk"_sv, 213)
                              , mp("denn"_sv, 214)
                              , mp("der"_sv, 215)
                              , mp("deswegen"_sv, 216)
                              , mp("die"_sv, 217)
                              , mp("dieser"_sv, 218)
                              , mp("dieses"_sv, 219)
                              , mp("digiales"_sv, 220)
                              , mp("dor"_sv, 221)
                              , mp("drck."_sv, 222)
                              , mp("drei"_sv, 223)
                              , mp("durch"_sv, 224)
                              , mp("e-ink"_sv, 225)
                              , mp("eBook"_sv, 226)
                              , mp("eBooks"_sv, 227)
                              , mp("ePub"_sv, 228)
                              , mp("eigenen"_sv, 229)
                              , mp("eigenlich"_sv, 230)
                              , mp("eigenmlichen"_sv, 231)
                              , mp("ein"_sv, 232)
                              , mp("eine"_sv, 233)
                              , mp("einen"_sv, 234)
                              , mp("einer"_sv, 235)
                              , mp("eines"_sv, 236)
                              , mp("einfach"_sv, 237)
                              , mp("einfaches"_sv, 238)
                              , mp("eingels."_sv, 239)
                              , mp("einigermaen"_sv, 240)
                              , mp("eins"_sv, 241)
                              , mp("einzelne"_sv, 242)
                              , mp("einzugeben."_sv, 243)
                              , mp("einzulsen,"_sv, 244)
                              , mp("elekronische"_sv, 245)
                              , mp("elekronischen"_sv, 246)
                              , mp("endlich"_sv, 247)
                              , mp("engangen:"_sv, 248)
                              , mp("er"_sv, 249)
                              , mp("erfll"_sv, 250)
#endif
#if 250 < SIZE
                              , mp("ersen"_sv, 251)
                              , mp("es"_sv, 252)
                              , mp("ewas"_sv, 253)
                              , mp("exra"_sv, 254)
                              , mp("fehlen"_sv, 255)
                              , mp("folg"_sv, 256)
                              , mp("fr"_sv, 257)
                              , mp("freien"_sv, 258)
                              , mp("ganz"_sv, 259)
                              , mp("ganze"_sv, 260)
                              , mp("ganzen"_sv, 261)
                              , mp("gefrag,"_sv, 262)
                              , mp("gehr"_sv, 263)
                              , mp("geh"_sv, 264)
                              , mp("gehs:"_sv, 265)
                              , mp("gemach"_sv, 266)
                              , mp("geschz."_sv, 267)
                              , mp("gib"_sv, 268)
                              , mp("habe"_sv, 269)
                              , mp("haben."_sv, 270)
                              , mp("ha"_sv, 271)
                              , mp("ha,"_sv, 272)
                              , mp("ha:"_sv, 273)
                              , mp("hehrer"_sv, 274)
                              , mp("heruner."_sv, 275)
                              , mp("hier"_sv, 276)
                              , mp("hl"_sv, 277)
                              , mp("iunes),"_sv, 278)
                              , mp("ich"_sv, 279)
                              , mp("im"_sv, 280)
                              , mp("in"_sv, 281)
                              , mp("indem"_sv, 282)
                              , mp("insallieren."_sv, 283)
                              , mp("insallier"_sv, 284)
                              , mp("insallier,"_sv, 285)
                              , mp("inegrier,"_sv, 286)
                              , mp("is"_sv, 287)
                              , mp("is."_sv, 288)
                              , mp("jeder"_sv, 289)
                              , mp("jez"_sv, 290)
                              , mp("kann"_sv, 291)
                              , mp("kann,"_sv, 292)
                              , mp("kann."_sv, 293)
                              , mp("kaufbaren"_sv, 294)
                              , mp("kaufen"_sv, 295)
                              , mp("kein"_sv, 296)
                              , mp("keine"_sv, 297)
                              , mp("keiner"_sv, 298)
                              , mp("klasse"_sv, 299)
                              , mp("klein,"_sv, 300)
#endif
#if 300 < SIZE
                              , mp("kleine"_sv, 301)
                              , mp("klicken."_sv, 302)
                              , mp("knapp"_sv, 303)
                              , mp("kommen."_sv, 304)
                              , mp("komm,"_sv, 305)
                              , mp("kopieren."_sv, 306)
                              , mp("kosenfrei"_sv, 307)
                              , mp("kurze"_sv, 308)
                              , mp("laden"_sv, 309)
                              , mp("ld"_sv, 310)
                              , mp("leich,"_sv, 311)
                              , mp("lesen."_sv, 312)
                              , mp("liegen"_sv, 313)
                              , mp("lieg"_sv, 314)
                              , mp("los."_sv, 315)
                              , mp("machen,"_sv, 316)
                              , mp("man"_sv, 317)
                              , mp("mche,"_sv, 318)
                              , mp("mche."_sv, 319)
                              , mp("mehr"_sv, 320)
                              , mp("meinem"_sv, 321)
                              , mp("meisen"_sv, 322)
                              , mp("mglich"_sv, 323)
                              , mp("mi"_sv, 324)
                              , mp("migeliefere"_sv, 325)
                              , mp("muss"_sv, 326)
                              , mp("nahe"_sv, 327)
                              , mp("namens"_sv, 328)
                              , mp("nchsen"_sv, 329)
                              , mp("nich"_sv, 330)
                              , mp("noch"_sv, 331)
                              , mp("ob"_sv, 332)
                              , mp("oder"_sv, 333)
                              , mp("preiswer"_sv, 334)
                              , mp("puppeneinfach"_sv, 335)
                              , mp("richig"_sv, 336)
                              , mp("schmerzfrei"_sv, 337)
                              , mp("schon"_sv, 338)
                              , mp("sechs"_sv, 339)
                              , mp("sehr"_sv, 340)
                              , mp("seine"_sv, 341)
                              , mp("sich"_sv, 342)
                              , mp("sind"_sv, 343)
                              , mp("sind."_sv, 344)
                              , mp("so"_sv, 345)
                              , mp("solchen"_sv, 346)
                              , mp("soll"_sv, 347)
                              , mp("sonyreader"_sv, 348)
                              , mp("sprechen."_sv, 349)
                              , mp("sare"_sv, 350)
#endif
#if 350 < SIZE
                              , mp("auch"_sv, 351)
                              , mp("un."_sv, 352)
                              , mp("um"_sv, 353)
                              , mp("und"_sv, 354)
                              , mp("uns"_sv, 355)
                              , mp("uner"_sv, 356)
                              , mp("uniled"_sv, 357)
                              , mp("verbinden,"_sv, 358)
                              , mp("verbrauch"_sv, 359)
                              , mp("verfgbaren"_sv, 360)
                              , mp("verloren."_sv, 361)
                              , mp("verwalen"_sv, 362)
                              , mp("vielen"_sv, 363)
                              , mp("vielmehr"_sv, 364)
                              , mp("vollen"_sv, 365)
                              , mp("von"_sv, 366)
                              , mp("vorher"_sv, 367)
                              , mp("was"_sv, 368)
                              , mp("welches"_sv, 369)
                              , mp("wenig"_sv, 370)
                              , mp("weniger"_sv, 371)
                              , mp("werden."_sv, 372)
                              , mp("wie"_sv, 373)
                              , mp("wieder"_sv, 374)
                              , mp("wird"_sv, 375)
                              , mp("wird,"_sv, 376)
                              , mp("wird."_sv, 377)
                              , mp("wo"_sv, 378)
                              , mp("wrde"_sv, 379)
                              , mp("wre."_sv, 380)
                              , mp("wurden"_sv, 381)
                              , mp("z.B."_sv, 382)
                              , mp("zu"_sv, 383)
                              , mp("zum"_sv, 384)
                              , mp("zur"_sv, 385)
                              , mp("zurcksezen"_sv, 386)
#endif
                              );

int main(int ac, char* av[])
{
    cf::string_view key(ac == 1? "five": av[1]);
    //std::cout << key << "->" << map[key] << "\n";
    std::cout << map << "\n";
}
